/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef psychic_CONSTANTS_H
#define psychic_CONSTANTS_H

#include "psychic_types.h"



class psychicConstants {
 public:
  psychicConstants();

};

extern const psychicConstants g_psychic_constants;



#endif
